url: http://maran.ro
name: Lucian Maran

markdown: redcarpet
redcarpet:
  extensions: ["tables","strikethrough"]
#markdown: kramdown

#highlighter: rouge
highlighter: pygments

permalink: /:year/:month/:day/:title/

# Disqus Comments
disqus_short_name: lmaran
disqus_show_comment_count: true
