url: http://maran.ro
name: Lucian Maran

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#markdown: kramdown

#highlighter: rouge
highlighter: pygments

permalink: /:year/:month/:day/:title/

# Disqus Comments
disqus_short_name: lmaran
disqus_show_comment_count: true
