url: http://maran.ro
name: Lucian Maran
markdown: redcarpet
extensions: [fenced_code_blocks]
pygments: false
permalink: /:year/:month/:day/:title/

# Disqus Comments
disqus_short_name: lmaran
disqus_show_comment_count: true
